# Generated by Django 3.2.4 on 2021-07-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('roll_no', models.CharField(max_length=9)),
                ('department', models.CharField(max_length=255)),
                ('graduation_year', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=12)),
                ('email_id', models.CharField(max_length=255)),
                ('preference_1', models.CharField(max_length=10)),
                ('preference_2', models.CharField(max_length=10)),
                ('preference_3', models.CharField(max_length=10)),
            ],
        ),
    ]
