# Generated by Django 3.2.4 on 2021-07-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteeinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='SOP',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mentee',
            name='preference_4',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentee',
            name='preference_5',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
