# Generated by Django 3.2.4 on 2021-07-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menteeinfo', '0004_auto_20210703_1527'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mentor',
            table=None,
        ),
    ]
