# Generated by Django 3.2.4 on 2021-07-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menteeinfo', '0005_alter_mentor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mentor',
            table='Mentors',
        ),
    ]
