# Generated by Django 3.2.4 on 2021-07-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteeinfo', '0009_alter_mentor_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
