# Generated by Django 3.2 on 2021-07-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteeinfo', '0010_alter_mentor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='contact_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='department',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='email_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='graduation_year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='roll_no',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
