# Generated by Django 3.2 on 2021-07-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteeinfo', '0013_auto_20210705_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='gray_out',
            field=models.CharField(default=1, max_length=1000, null=True),
        ),
    ]
