# Generated by Django 3.2 on 2021-07-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteeinfo', '0014_alter_mentor_gray_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='hits',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
