# Generated by Django 3.2 on 2021-07-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteeinfo', '0016_alter_mentor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='experience',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
