# Generated by Django 3.2 on 2021-07-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteeinfo', '0018_auto_20210707_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='gray_out',
            field=models.CharField(default=1, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='hits',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
