# Generated by Django 3.2 on 2021-07-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteeinfo', '0019_auto_20210707_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='preference_1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='preference_2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='preference_3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='preference_4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='preference_5',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
