# Generated by Django 3.2 on 2021-07-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteeinfo', '0020_auto_20210707_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='SOP',
            field=models.TextField(null=True),
        ),
    ]
