# Generated by Django 3.2.4 on 2021-07-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteeinfo', '0021_alter_mentee_sop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
