# Generated by Django 3.2 on 2021-07-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menteeinfo', '0022_alter_mentor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='degree',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='degree_other',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mentee',
            name='suggestion',
            field=models.TextField(null=True),
        ),
    ]
