# Generated by Django 3.2 on 2021-07-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menteeinfo', '0023_auto_20210712_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='graduation_year',
        ),
    ]
