# Generated by Django 3.2 on 2021-06-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('rollno', models.CharField(max_length=9)),
                ('department', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('graduation_year', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=255)),
                ('experience', models.TextField()),
                ('contact', models.CharField(max_length=12)),
                ('mail', models.CharField(max_length=255)),
                ('no_of_mentees', models.CharField(max_length=255)),
                ('referral', models.CharField(max_length=255)),
                ('suggestions', models.TextField()),
                ('analytics', models.CharField(max_length=50)),
                ('consultancy', models.CharField(max_length=50)),
                ('finance', models.CharField(max_length=50)),
                ('FMCG', models.CharField(max_length=50)),
                ('software', models.CharField(max_length=50)),
                ('core', models.CharField(max_length=100)),
                ('other_mentorship', models.CharField(max_length=100)),
            ],
        ),
    ]
