# Generated by Django 3.2 on 2021-06-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='degree_other',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
